### ISSUE TITLE
Libfuncs: starknet testing

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#103]
[Sierra implementation](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra/src/extensions/modules/starknet/testing.rs)
  - [ ] set_block_number
  - [ ] set_block_timestamp
  - [ ] set_caller_address
  - [ ] set_contract_address
  - [ ] set_sequencer_address

**Comment by vibenedict** [comment]
Hi, i will like to take up this issue.
