### ISSUE TITLE
Debugger support

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#12]
Examine MLIR's and melior's ability to add support for running generated programs under lldb with DWARF information.

**Comment by edg-l** [comment]
This can be done using 

https://mlir.llvm.org/docs/Dialects/Builtin/#location-attributes

and more with

https://mlir.llvm.org/docs/Dialects/LLVM/#llvmintrdbgvalue-mlirllvmdbgvalueop

**Comment by edg-l** [comment]
closing as completed
