### ISSUE TITLE
Document how entrypoints work

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#258]
The mechanism via which entrypoints into 
- a generated binary and 
- an execution engine set up with a generated module 
are generated, set up, and called, in both standalone cairo programs and contracts should be documented.
- how the compiler generates the entrypoints and represents them with MLIR
- how an entrypoint is selected for execution through the API and command line runner
- How arguments are passed to the entrypoint (can link to relevent existing documentation)

**Comment by Immanuelolivia1** [comment]
Please can I be assigned this? @igaray

**Comment by Osatuyi** [comment]
Hi @igaray can I be assigned this issue, please.

**Comment by edg-l** [comment]
I believe this is now done here: https://github.com/lambdaclass/cairo_native/blob/main/docs/execution_walkthrough.md 

closing as done then
