### ISSUE TITLE
Document how gas and step counting in the cairo and cairo-vm works

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#264]
Gas cost computation and use, and the counting of steps involves several moving parts, in cairo and cairo-vm.
They are both included in the execution info returned by the execution of a cairo contract and are required to compute fees in downstream libraries. 
The output of this issue should be documentation of these other projects and a design of how the equivalent works or should work in cairo-native.

**Comment by Osatuyi** [comment]
Can I be assigned this issue please?

**Comment by edg-l** [comment]
I believe this is done in https://github.com/lambdaclass/cairo_native/blob/main/docs/gas_builtin_accounting.md
