### ISSUE TITLE
Add implementation for `CoreTypeConcrete::NonZero` in outputs comparison

### ISSUE THREAD

**Issue by entropidelic** [lambdaclass/cairo_native#303]
The cairo corelib was recently changed, adding a `NonZero` type in the outputs of some functions, for example `ec_point_from_x` does not exist anymore, only `ec_point_from_x_nz`.
As this type is now returned, we need an implementation for it in the results comparisons done by the [`compare_outputs`](https://github.com/lambdaclass/cairo_native/blob/0999c160d4d248646b269645a180a87c9a6c01e3/tests/common.rs#L335) function.

For the moment there is one test being ignored due to this, `ec_point_from_x_small`. We should code the implementation and make the test pass.

**Comment by fmoletta** [comment]
Fixed by #386
