### ISSUE TITLE
AOT Runner Design

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#348]
- [x] Find a way to output a shared object from the LLVM pipeline
- [x] Find a way to link and load said shared object into the running process
- [x] Gather requirements on entrypoints and parameter and return values passing
- [x] Rename NativeExecutor to NativeJITExecutor
- [x] Create NativeAOTExecutor stub

The output of this issue should be a design and specification for the AOT compilation api, mechanism and runner.

**Comment by edg-l** [comment]
Some useful links related

https://github.com/llvm/llvm-project/blob/llvmorg-17.0.5/mlir/lib/Tools/mlir-translate/MlirTranslateMain.cpp

https://mlir.llvm.org/doxygen/classmlir_1_1LLVM_1_1ModuleTranslation.html#ac7e657a04e78a09ffd38c2f6cde6b905

https://mlir.llvm.org/docs/TargetLLVMIR/

https://mlir.llvm.org/doxygen/namespacemlir.html#adc149979459c3123124db882fb765dba

**Comment by edg-l** [comment]
first bullet point done in https://github.com/lambdaclass/cairo_native/pull/352

**Comment by igaray** [comment]
Completed in #390
