### ISSUE TITLE
Investigate alignment compatibility with felt252 (x86_64 arch)

### ISSUE THREAD

**Issue by toni-calvin** [lambdaclass/cairo_native#367]
Investigate the test called `test_alignment_compatibility_felt252` and `test_alignment_compatibility_u128` and why is it failing. (only on x86_64 arch)

**Comment by vibenedict** [comment]
Hi, i will like to take up this issue.

**Comment by edg-l** [comment]
This is fixed on main with the llvm and rust 1.78 update
