### ISSUE TITLE
Incorrect payloads in complex enums

### ISSUE THREAD

**Issue by DomHenderson** [lambdaclass/cairo_native#447]
As can be seen in the `enum_init_nested_*` tests in #445, enums are being returned with incorrect payloads, though whether this is because they are stored incorrectly or loaded/returned incorretly I cannot say.

**Comment by azteca1998** [comment]
I can't seem to replicate the issue. I've tried every nested enum program from your PR and I'm getting the expected results running with `cairo-native-run`.

Could the issue be only when felts are involved? We changed the library we used for felts and now their limbs are debug-printed using Montgomery form, which is annoying.

**Comment by azteca1998** [comment]
Nevermind I see what you mean. The tests fail when comparing with the VM.
I'll look into it.
