### ISSUE TITLE
Kakarot tests 

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#450]
This [branch](https://github.com/kkrt-labs/ef-tests/pull/628) of Kakarot's fork of the ethereum foundation tests integrates with Starknet in Rust running Native. 

You can run it with 
`cargo test -p ef-testing --features "v1,native" test_execute_simple_contract`

A test which runs the full validate and execute for calling a small evm contract, gets the below error:

![Screenshot 2024-02-21 at 18 58 44](https://github.com/lambdaclass/cairo_native/assets/167193/e73fa434-0d5e-42ab-a551-8986d150f7d4)

running just validation will also fail (skipping execution):

![Screenshot 2024-02-21 at 19 02 51](https://github.com/lambdaclass/cairo_native/assets/167193/88da9646-90b9-4e83-b218-6284c7c6c0c7)

**Comment by greged93** [comment]
Setup should be ok with `make setup-kakarot-v0 && make setup-kakarot-v1`.

**Comment by azteca1998** [comment]
I've implemented a fix for the bug you had, but I can't check if there are more bugs in my machine because it won't compile your branch due to unknown features in dependencies. Could you check if there are more bugs? Thanks.

**Comment by greged93** [comment]
Will do now
