### ISSUE TITLE
bug: immarg operand has non-immediate parameter

### ISSUE THREAD

**Issue by greged93** [lambdaclass/cairo_native#456]
Getting the below error running a test on the Kakarot test suite with native while running:
- native: https://github.com/lambdaclass/cairo_native/commit/1844307d38633d9774cc14fcd3cd183b1989d2e5
- starknet_in_rust: 5e44291002d555bb8e88b7c4b04de1c36632723e (https://github.com/lambdaclass/starknet_in_rust/pull/1243)

Causes the below issue:
```
immarg operand has non-immediate parameter
  %322 = zext i32 %313 to i64
  call void @llvm.memcpy.inline.p0.p0.i64(ptr %323, ptr %321, i64 %322, i1 false)
immarg operand has non-immediate parameter
  %130 = zext i32 %88 to i64
  call void @llvm.memcpy.inline.p0.p0.i64(ptr %131, ptr %129, i64 %130, i1 false)
immarg operand has non-immediate parameter
  %184 = zext i32 %88 to i64
  call void @llvm.memcpy.inline.p0.p0.i64(ptr %185, ptr %183, i64 %184, i1 false)
immarg operand has non-immediate parameter
  %290 = zext i32 %281 to i64
  call void @llvm.memcpy.inline.p0.p0.i64(ptr %291, ptr %289, i64 %290, i1 false)
immarg operand has non-immediate parameter
  %76 = mul i64 %75, 32
  call void @llvm.memcpy.inline.p0.p0.i64(ptr %77, ptr %74, i64 %76, i1 false)
immarg operand has non-immediate parameter
  %105 = mul i64 %104, 32
  call void @llvm.memcpy.inline.p0.p0.i64(ptr %106, ptr %103, i64 %105, i1 false)
immarg operand has non-immediate parameter
  %164 = zext i32 %128 to i64
  call void @llvm.memcpy.inline.p0.p0.i64(ptr %165, ptr %163, i64 %164, i1 false)
immarg operand has non-immediate parameter
  %405 = zext i8 %390 to i64
  call void @llvm.memcpy.inline.p0.p0.i64(ptr %406, ptr %404, i64 %405, i1 false)
```

**Comment by azteca1998** [comment]
Hello, I've made a fix based on your error description, but I can't test it because it won't build on my machine.

Trying to build your branch as is causes the compiler to emit a bunch of unstable and unknown simd features. If I remove `rust-toolchain` and update both `cargo update` and `rustup update` then it fails to compile with a `mismatched types` error. Could you try it and check if it fixes the bug?

**Comment by greged93** [comment]
tested locally, getting another error which might not be related to native this time, but `immarg operand has non-immediate parameter` seems fixed!
