### ISSUE TITLE
Feature: Add a syscall handler to cairo-native-test

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#467]
So the cairo keccak tests can be run.

**Comment by AryanGodara** [comment]
Hi @edg-l @igaray Can I please work on this issue?
I'll get it done by Monday :D
Could you also please assign this to me

**Comment by edisontim** [comment]
Gm, is this issue still up to date and if so could I take this :) ?

**Comment by edg-l** [comment]
> Gm, is this issue still up to date and if so could I take this :) ?

Hello, this issue is already done, sorry for not closing it beforehand!
