### ISSUE TITLE
Increase coverage of the array libfuncs

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#480]
The function `build_snapshot_pop_back` in `src/libfuncs/array.rs` could use a good test to increase coverage.

**Comment by Gerson2102** [comment]
I would like to take this one. But i think that i'm gonna need some guidance if that is not a problem for the team.

**Comment by igaray** [comment]
No problem, feel free to take a look and ask anything. We're also on telegram in the Lambda Starknet channel

**Comment by azteca1998** [comment]
You may use the currently available tests as well as my [array refactoring PR](https://github.com/lambdaclass/cairo_native/pull/461) as a guide or starting point.

**Comment by Gerson2102** [comment]
@azteca1998 on that PR,  i guess i should focus on the packages test, because inside of them are the different test files. And btw, i should ask questions on the Lambda Starknet like the last one that i already did?

**Comment by azteca1998** [comment]
I meant the unit tests in `src/libfuncs/array.rs`. The integration tests (the `tests/` folder) was modified to fix something else.

As for the questions, if they're related to the issues and you want me to answer you should probably ask them on the issues. This way I'll eventually see them and won't be lost after a while due to the number of messages.

**Comment by 0xSileo** [comment]
If anyone's working on this, I'd love to help, feel free to contact me and assign me to a specific task !

**Comment by Gerson2102** [comment]
Since i dont want to spam this on Telegram, im gonna do it here. These are the two tests that i have now:


````
#[test]
    fn snapshot_pop_back_array() {
        let program = load_cairo!(
            use array::ArrayTrait;

            fn run_test() -> (Array<u32>, Option<u32>) {
                let mut numbers = ArrayTrait::new();
                numbers.append(1_u32);
                numbers.append(2_u32);
                numbers.append(3_u32);
                let popped = numbers.pop_back();
                (numbers, popped)
            }
        );

        let result = run_program(&program, "run_test", &[]).return_value;

        assert_eq!(
            result,
            jit_struct!(
                jit_enum!(0, jit_struct!(1u32.into(), 2u32.into())),
                jit_enum!(0, 3u32.into())
            )
        );
    }

    #[test]
    fn snapshot_pop_back_empty_array() {
        let program = load_cairo!(
            use array::ArrayTrait;

            fn run_test() -> (Array<u32>, Option<u32>) {
                let mut numbers = ArrayTrait::new();
                let popped = numbers.pop_back();
                (numbers, popped)
            }
        );

        let result = run_program(&program, "run_test", &[]).return_value;

        assert_eq!(
            result,
            jit_struct!(jit_enum!(0, jit_struct!()), jit_enum!(1, jit_struct!()))
        );
    }
````
    
    
I understand that i have to test the `build_snapshot_pop_back()` function, and the other tests that are inside of that file they have helped me a lot. But when i run the tests now, throws the following error:


```
failures:

---- libfuncs::array::test::snapshot_pop_back_array stdout ----
error: Method `pop_back` could not be called on type `core::array::Array::<?0>`.
Candidate `SpanTrait::pop_back` inference failed with: Type mismatch: `core::array::Array::<core::integer::u32>` and `core::array::Span::<?4>`
 --> /tmp/test_UOkVer.cairo:5:13
    numbers.pop_back(); (numbers, popped)
            ^******^

```

And for the other test is the same. I think that there can be more tests, but I'm struggling to understand what is doing in detail that function.

**Comment by azteca1998** [comment]
Hello, it seems you're trying to `pop_back` from an array directly. Note that the libfunc works only on spans, this means you need to create a span from the array before you'll be able to `pop_back`, like this:
```cairo
let mut numbers = numbers.span();
```

**Comment by tcoratger** [comment]
Is there anything left to do here or should we close?
