### ISSUE TITLE
Increase coverage of the AOT executor and cache

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#481]
The functions in [src/cache/aot.rs](https://app.codecov.io/gh/lambdaclass/cairo_native/blob/main/src%2Fcache%2Faot.rs) and [src/executor/aot.rs](https://app.codecov.io/gh/lambdaclass/cairo_native/blob/main/src%2Fexecutor%2Faot.rs) are not covered by tests

**Comment by Prabhat1308** [comment]
Hi. I would like to take up this issue

**Comment by igaray** [comment]
go for it! feel free to ask anything about the issue, or ping us in telegram

**Comment by greged93** [comment]
hey @igaray this seems stale, can I take it?
