### ISSUE TITLE
Increase coverage of the JIT values 

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#482]
The code in [src/values.rs](https://app.codecov.io/gh/lambdaclass/cairo_native/blob/main/src%2Fvalues.rs) is under-covered by our tests.

**Comment by brolag** [comment]
Hi @igaray, I'd like to try this one!

**Comment by g4titan** [comment]
hello @igaray, assign this task to me

**Comment by igaray** [comment]
I think @brolag had first dibs, if they responde by EOD today I'll assign them, otherwise I'll let you know @g4titan

**Comment by g4titan** [comment]
alright, thanks!

**Comment by brolag** [comment]
Hi @g4titan I had some issues trying to solve this so please feel free to take this issue if you want. cc: @igaray

**Comment by rvalenciano** [comment]
hey @igaray how are you? I'm a first time contributor and would like to tackle this one :)

**Comment by igaray** [comment]
Closed by #572, #579, and #589
