### ISSUE TITLE
Increase coverage of the utilities module

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#483]
The coverage of [src/utils.rs](https://app.codecov.io/gh/lambdaclass/cairo_native/blob/main/src%2Futils.rs) could be improved somewhat.

**Comment by wugalde19** [comment]
Hi @igaray 
I'd love to start contributing on this project
Do you think this issue could be a good one to start with?
Or do you consider that maybe issues #471 or #472 could be better?

**Comment by igaray** [comment]
Hi @wugalde19 ! I think this one is probably the easiest of the three. After that `test_u256_div_mod_n` (https://github.com/lambdaclass/cairo_native/issues/472) although some knowledge of felt operations and taking a good look at how we implement them is likely required. 
The issue related to byte arrays test failures (https://github.com/lambdaclass/cairo_native/issues/471) is likely related to other things we are currently working on.

**Comment by wugalde19** [comment]
@igaray Understood
In that case, I'm gonna take care of this one first
If #472 is not assigned by the moment I finish this one, then I'll take care of it as well

Thanks for the opportunity.
Please let me know if there's a chat where I can go and ask questions

**Comment by igaray** [comment]
You can ask question in the Lambda Starknet telegram channel https://t.me/LambdaStarkNet

**Comment by wugalde19** [comment]
> You can ask question in the Lambda Starknet telegram channel https://t.me/LambdaStarkNet

Thanks @igaray 
I just joined the channel

**Comment by igaray** [comment]
Closed by #583
