### ISSUE TITLE
Test the switch libfunc helper function 

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#484]
The `switch` function in `src/libfuncs.rs` is a helper function used to implement libfuncs and is not directly tested, although the code generated is tested in other places. It would be good to find a way to test it directly and increase [coverage](https://app.codecov.io/gh/lambdaclass/cairo_native/blob/main/src%2Flibfuncs.rs) of the libfuncs module.

**Comment by Fu8ionDiego** [comment]
Hi,

I would love to work on this issue.

Thanks, 

Diego

**Comment by igaray** [comment]
@Fu8ionDiego still interested? otherwise I'll asign @g4titan

**Comment by Fu8ionDiego** [comment]
Hi @g4titan, yes I am still interested. Thanks

**Comment by g4titan** [comment]
hey @Fu8ionDiego , wrong tag, you should tag @igaray

**Comment by tcoratger** [comment]
Can I work on this?

**Comment by igaray** [comment]
Assigned!
