### ISSUE TITLE
Increase coverage of the execution result module 

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#485]
The `from_execution_result ` function in [src/execution_result.rs](https://app.codecov.io/gh/lambdaclass/cairo_native/blob/main/src%2Fexecution_result.rs#src/execution_result.rs) is tested and covered but many of the expected failure conditions are not (see the possible `Err` values that can be returned. It would be a desireable to have tests to also ensure proper failure as well as the happy path.

**Comment by snehasharma76** [comment]
Please assign this issue to me.

**Comment by greged93** [comment]
@igaray down to complete this one !
