### ISSUE TITLE
 Test the debug info module

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#486]
The [src/debug_info.rs](https://app.codecov.io/gh/lambdaclass/cairo_native/blob/main/src%2Fdebug_info.rs#src/debug_info.rs) module is barely tested and could use some coverage.

**Comment by lordshashank** [comment]
Hey, I can work on this one.

**Comment by lordshashank** [comment]
@igaray , wanted to know where to configure tests for module, should I write tests in same file, or configure them in tests folder, or something else?

**Comment by igaray** [comment]
So far we've been putting them in the same file. If it becomes too large we can see about moving the test module to a separate file. Thanks!

**Comment by edisontim** [comment]
Gm, can I take this ?

**Comment by edg-l** [comment]
There is no longer a debug info module
