### ISSUE TITLE
Increase coverage of the context module

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#487]
The [`compile_with_metadata`](https://app.codecov.io/gh/lambdaclass/cairo_native/blob/main/src%2Fcontext.rs#L86) function is not tested.

**Comment by Ash20pk** [comment]
@igaray I can pick this up

**Comment by tcoratger** [comment]
@igaray As I see the coverage file, this can be closed no? as the `compile_with_metadata` seems to be covered now, no?

**Comment by igaray** [comment]
yeah, agreed.
