### ISSUE TITLE
Update the melior dependency to 0.17.0

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#493]
Melior is the crate that allows us to use MLIR in rust, there is a new version `0.17.0` that changes a bit the api (mainly argument order on integer attributres), so its a bit more work than just changing the version on the toml file.

**Comment by AryanGodara** [comment]
Can I work on this one @edg-l ?

**Comment by edg-l** [comment]
> Can I work on this one @edg-l ?

sure thing!
