### ISSUE TITLE
Refactor bool libfuncs to use the BlockExt trait

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#519]
See: https://github.com/lambdaclass/cairo_native/pull/518

Refactor the code implementing the libfuncs to use the trait methods from `BlockExt`.

**Comment by vibenedict** [comment]
Good day, can you assign this task to me.

**Comment by wugalde19** [comment]
@edg-l 
Hi again
Hope you are doing great.
Looking forward to contributing and learn more about the project

If not assigned yet, can I get the chance to work on this issue?

**Comment by vibenedict** [comment]
Hi @wugalde19, I have started working on  this issue already.
I  think there are a couple of open issues you can pick from the issues tab.

**Comment by igaray** [comment]
Closed by #563
