### ISSUE TITLE
 Refactor bitwise libfuncs to use the BlockExt trait

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#520]
See: https://github.com/lambdaclass/cairo_native/pull/518

Refactor the code implementing the libfuncs to use the trait methods from `BlockExt`.

**Comment by Gerson2102** [comment]
Hello, can i work on this one? And btw i still figuring out what i have to do.

**Comment by Alvarodb** [comment]
@edg-l I've reviewed the PR and understand the refactor that's being implemented. If this task becomes available, I'm ready to jump in.

**Comment by Gerson2102** [comment]
@edg-l hello mate. I have a question in this issue. I think that i understand what i have to do. But something that i still dont get it, is the fact that, the functions that can be refactored regards to the PR linked in this issue, they are not part of bitwise libfuncs. So how should I refactor bitwise?

**Comment by igaray** [comment]
did you check this PR out? https://github.com/lambdaclass/cairo_native/pull/518/files

it added a file src/block_ext.rs which has a trait, BlockExt, and implements that trait for the melior Block type. 
one of the functions it adds is append_op_result, whose implementation does the same thing that the bitwise build function does several times. 

so the bitwise libfunc builder should use that trait implementation function to append the operations and get the result

**Comment by Gerson2102** [comment]
> did you check this PR out? https://github.com/lambdaclass/cairo_native/pull/518/files
> 
> it added a file src/block_ext.rs which has a trait, BlockExt, and implements that trait for the melior Block type. one of the functions it adds is append_op_result, whose implementation does the same thing that the bitwise build function does several times.
> 
> so the bitwise libfunc builder should use that trait implementation function to append the operations and get the result

So this:
``let logical_and = entry
        .append_operation(arith::andi(lhs, rhs, location))
        .result(0)?
        .into();
``

To something like this right?:
``let logical_xor = entry.append_op_result(arith::xori(lhs, rhs, location));
``
