### ISSUE TITLE
 Refactor box libfuncs to use the BlockExt trait

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#521]
See: https://github.com/lambdaclass/cairo_native/pull/518

Refactor the code implementing the libfuncs to use the trait methods from `BlockExt`.

**Comment by FeliGR** [comment]
Hello @edg-l,

I noticed that @gerson initially asked about this issue. I've reviewed the details and understand the task. If he chooses not to pursue it further, I would be interested in working on this. Could you kindly assign it to me if it becomes available?

**Comment by Gerson2102** [comment]
Pls assign this to @FeliGR

**Comment by vibenedict** [comment]
i will like to jump on it

**Comment by adriangarro** [comment]
@edg-l  is this issue still pending to solve?
