### ISSUE TITLE
Refactor cast libfuncs to use the BlockExt trait

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#523]
See: https://github.com/lambdaclass/cairo_native/pull/518

Refactor the code implementing the libfuncs to use the trait methods from `BlockExt`.

**Comment by kamuik16** [comment]
Hey! I would like to be assigned to this once the event starts! Thanks!

**Comment by RajeshRk18** [comment]
Cab you please assign me? I am almost done with this issue.
