### ISSUE TITLE
Refactor enum libfuncs to use the BlockExt trait

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#526]
See: https://github.com/lambdaclass/cairo_native/pull/518

Refactor the code implementing the libfuncs to use the trait methods from `BlockExt`.

**Comment by PabloVillaplana** [comment]
Hello @edg-l I would love to be part of this effort! 👷🏽‍♂️, thanks (I am in OD Hack telegram, ready to start on Monday 🫡)

**Comment by g4titanx** [comment]
hello @edg-l , i would love to work on this

**Comment by edg-l** [comment]
> hello @edg-l , i would love to work on this

Sure thing!
