### ISSUE TITLE
Refactor gas libfuncs to use the BlockExt trait

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#527]
See: https://github.com/lambdaclass/cairo_native/pull/518

Refactor the code implementing the libfuncs to use the trait methods from `BlockExt`.

**Comment by muheebyusufbaba1** [comment]
I will like to work on this

**Comment by mananbordia** [comment]
@edg-l Looks like @muheebyusufbaba1 hasn't got chance to work on this issue.
I would like to work on this one, can you please assign it to me ?

**Comment by muheebyusufbaba1** [comment]
I'm still working on it go get your other issues sir

**Comment by mananbordia** [comment]
@muheebyusufbaba1 Awesome, since it was like 2 weeks since your last comment and no PR was raised, I thought you might have lost track on this. Thanks for the update, I'll pick some other task.

**Comment by muheebyusufbaba1** [comment]
Last time I checked 2 weeks was 14 days

**Comment by mananbordia** [comment]
Cool.

<img width="921" alt="Screenshot 2024-05-01 at 12 20 44 AM" src="https://github.com/lambdaclass/cairo_native/assets/45929094/0d8bd23f-fbe2-42dd-a62d-7d7ce3b423e1">

Won't argue with you as I just came here to take the starknet community forward. Peace ✌️

**Comment by muheebyusufbaba1** [comment]
![image](https://github.com/lambdaclass/cairo_native/assets/134698940/3418e591-3327-4737-bac2-8f2df79c1ce5)

**Comment by igaray** [comment]
Closed by #571

**Comment by mananbordia** [comment]
Lol, didn't know we can also get PRs merged for issues that not assigned to us.
Wish I knew this earlier 😅
