### ISSUE TITLE
Refactor mem libfuncs to use the BlockExt trait

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#528]
See: https://github.com/lambdaclass/cairo_native/pull/518

Refactor the code implementing the libfuncs to use the trait methods from `BlockExt`.

**Comment by jbmkahdeksan** [comment]
hello!
is this available?
I am interested in contributing:)

**Comment by wugalde19** [comment]
@edg-l 
Hi again
Hope you are doing great.
Looking forward to contributing and learning more about the project

If not assigned yet, can I get the chance to work on this issue?

**Comment by pefontana** [comment]
@jbmkahdeksan Assigned
