### ISSUE TITLE
Refactor pedersen libfuncs to use the BlockExt trait

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#529]
See: https://github.com/lambdaclass/cairo_native/pull/518

Refactor the code implementing the libfuncs to use the trait methods from `BlockExt`.

**Comment by Saraahma** [comment]
gh pr checkout 498

**Comment by TAdev0** [comment]
Hi @edg-l  , may I be assigned to this issue and work on it after your PR is merged?
