### ISSUE TITLE
Refactor poseidon libfuncs to use the BlockExt trait

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#530]
See: https://github.com/lambdaclass/cairo_native/pull/518

Refactor the code implementing the libfuncs to use the trait methods from `BlockExt`.

**Comment by Saraahma** [comment]
hi  learn web 3

**Comment by Saraahma** [comment]
hi

**Comment by Saraahma** [comment]
hello

**Comment by princeibs** [comment]
Can I hop on this?  @edg-l

**Comment by edg-l** [comment]
> Can I hop on this? @edg-l

Sure! assigned

**Comment by princeibs** [comment]
Alright. For the main time, I will just get myself familiar with the codebase while waiting for the PR to be merged

**Comment by edisontim** [comment]
Gm @princeibs are you still working on this?

**Comment by TropicalDog17** [comment]
Hi @edg-l @igaray could I work on this issue? Thanks!

**Comment by adrianvrj** [comment]
Hi, is this still available? I am pretty sure I can work on this and deliver it fast! :)

**Comment by PhantomOz** [comment]
Hello @edg-l and @igaray, I am a smart contract developer and I can execute this task if it is still available.

**Comment by RajeshRk18** [comment]
Hey, I don't know if the issue is assigned to the order of comments. But, I've experience doing the refactoring. Shall I take up this?

**Comment by od-hunter** [comment]
Can I be assigned this issue, this is my first time contributing and I’d love to be given the opportunity.
