### ISSUE TITLE
Refactor struct libfuncs to use the BlockExt trait

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#531]
See: https://github.com/lambdaclass/cairo_native/pull/518

Refactor the code implementing the libfuncs to use the trait methods from `BlockExt`.

**Comment by manoahLinks** [comment]
can i hop on this ?

**Comment by wugalde19** [comment]
Hi, Is this still available?
If so, I'd like to work on this one

**Comment by edg-l** [comment]
@manoahLinks are you up for this?

**Comment by manoahLinks** [comment]
hi @edg-l i am trying to make a push, but its showing i don't have access. please help out

**Comment by igaray** [comment]
Hello @manoahLinks Have you forked the repo and issued the PR from your fork to this fork's main branch?

**Comment by manoahLinks** [comment]
retried again, and its not successful. thanks
