### ISSUE TITLE
Refactor starknet libfuncs to use the BlockExt trait

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_native#532]
See: https://github.com/lambdaclass/cairo_native/pull/518

Refactor the code implementing the libfuncs to use the trait methods from `BlockExt`.

Note: this one is more work than the others.

**Comment by manoahLinks** [comment]
Hi, cant seem to find BlockExt trait within the codebase, do i have to create this trait, pls explain more about this issue

**Comment by manoahLinks** [comment]
can i hop on this ?

**Comment by fabrobles92** [comment]
@edg-l  Hello, I would like to work on this issue :)

**Comment by RajeshRk18** [comment]
@edg-l Can I work on this issue?

**Comment by RajeshRk18** [comment]
Hey @fabrobles92 , are you taking this issue?

**Comment by RajeshRk18** [comment]
@edg-l Can you assign me? I'll work on this

**Comment by RajeshRk18** [comment]
Tests are passing. Please assign this issue!!

**Comment by vibenedict** [comment]
i will like to jump on it

**Comment by azteca1998** [comment]
Done by #694.
