### ISSUE TITLE
Ensure that all `llvm.alloca`s are on the helper's init block.

### ISSUE THREAD

**Issue by azteca1998** [lambdaclass/cairo_native#543]
All `llvm.alloca` (and their dependencies, which should be constants only) should be appended to the init block, otherwise the tail recursion mechanism will keep allocating more and more stack space every iteration, which is precisely what we want to avoid by using that mechanism.

**Comment by rvalenciano** [comment]
Hey, whats up! I'm a first time contributor and would love to introduce myself in the codebase. Let me know if I can grab this or any other issue :)

**Comment by Gerson2102** [comment]
@azteca1998 Hello mate. When you say `llvm.alloca` you mean `llvm::alloca`? Do i have to check in libfuncs for those things?
Where is the init block?

**Comment by azteca1998** [comment]
Hello,

With `llvm.alloca` I'm referring to the `alloca` instructions in the `llvm` dialect. In MLIR they're written as `llvm.alloca`, but we have them available as `llvm::alloca` in Rust.

The `llvm.alloca` instruction accepts other values as arguments. In your example, the argument would be `value_len`. They also need to be on the init block, otherwise the generated MLIR would be invalid.

All `llvm.alloca` operations must be in the init block instead of `entry` or whatever other local block every libfunc has. I know there's at least one place where it's not in the init block.

**Comment by Gerson2102** [comment]
> Hello,
> 
> With `llvm.alloca` I'm referring to the `alloca` instructions in the `llvm` dialect. In MLIR they're written as `llvm.alloca`, but we have them available as `llvm::alloca` in Rust.
> 
> The `llvm.alloca` instruction accepts other values as arguments (which are dependencies). In your example, the argument would be `value_len`. They also need to be on the init block, otherwise the generated MLIR would be invalid.
> 
> All `llvm.alloca` operations must be in the init block instead of `entry` or whatever other local block every libfunc has. I know there's at least one place where it's not in the init block.

In the previous example, `llvm::alloca` and the dependencie, are in the init block right? Because I'm using the helper where is located the init function.

When you say `entry`, is the variable we use to call `init_block()` right? And we dont want that, we want the LibFuncHelper, am I right?

**Comment by azteca1998** [comment]
`helper.init_block()` is the block at which the operation is appended. We want to append the init block (`helper.init_block()`) instead of `entry` (the default block for each libfunc), or any other block internally created within the libfunc (only present in complex libfuncs).

Basically, every `.append_operation(llvm::alloca(...))` and its dependencies (the constant) should append to `helper.init_block()`.

**Comment by Gerson2102** [comment]
Ok. And i have to look through all the code of the project, not just the libfuncs directory?

**Comment by azteca1998** [comment]
Ideally yes, but outside the libfuncs (and a few helper functions I think) you won't have the `helper`. If you find something outside libfuncs' implementations just letting us know is fine, we'll fix it later.

**Comment by Gerson2102** [comment]
> This is already done

In my PR of someone else did this? @edg-l
