### ISSUE TITLE
Issue with Dockerfile

### ISSUE THREAD

**Issue by varex83** [lambdaclass/cairo_native#578]
I was trying run Juno node with blockifier + cairo native, and got stuck on building the Dockerfile, after that I checked [Dockerfile](https://github.com/lambdaclass/cairo_native/blob/main/Dockerfile) in the cairo native repo from main branch (rev. e9bc96aaa408e388f079c1f95ef8427e1fa52abe), and got strange error:

<img width="896" alt="image" src="https://github.com/lambdaclass/cairo_native/assets/35969035/26dbc93a-2a69-4fdc-a83f-f7c012081631">

--- 

<details>
<summary>Dockerfile</summary>

```dockerfile
FROM debian:12

# Install dependencies
RUN apt update -y && apt install -y lsb-release \
    wget \
    curl \
    git \
    build-essential \
    libclang-dev \
    libz-dev \
    libzstd-dev

# Install LLVM 17
RUN echo "deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-17 main" > /etc/apt/sources.list.d/llvm-17.list
RUN echo "deb-src http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-17 main" >> /etc/apt/sources.list.d/llvm-17.list
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN apt update -y && apt install -y llvm-17 \
    libmlir-17-dev \
    mlir-17-tools \
    libpolly-17-dev

# Install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Copy cairo_native code
COPY . /cairo_native/

# Compile cairo_native
WORKDIR /cairo_native/
ENV MLIR_SYS_170_PREFIX=/usr/lib/llvm-17
ENV LLVM_SYS_170_PREFIX=/usr/lib/llvm-17
ENV TABLEGEN_170_PREFIX=/usr/lib/llvm-17
RUN make deps
RUN make build
```

</details>

I'm building it with `docker build .`. Let me know if you need more details! 🙏

**Comment by varex83** [comment]
thanks for the response a lot!

**Comment by greged93** [comment]
had the same error and @tcoratger gave me a workaround: `docker build --platform linux/amd64 -t image_tag .`
