### ISSUE TITLE
Implement CoreTypeConcrete::Bytes31 return type

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo_native#596]
Implement the parse result for CoreTypeConcrete::Bytes31
https://github.com/lambdaclass/cairo_native/blob/ddfd28217c10f7202a03f10234f0a19113c46904/src/executor.rs#L786

We should be able to run the bytes31_ret.cairo test
https://github.com/lambdaclass/cairo_native/blob/e89d38ad2f01bbd85c9f9de0b37841ac98661b50/tests/tests/cases.rs#L113

**Comment by greged93** [comment]
hey @pefontana, I'm down to try this is possible

**Comment by pefontana** [comment]
Hi @raizo07 !
Sorry, I am currently implementing it!
But if you want to take another CoreTypeConcrete return type, you can ask us and implement it!
