### ISSUE TITLE
Implement CoreTypeConcrete::SquashedFelt252Dict return type

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo_native#601]
Implement the parse result for CoreTypeConcrete::SquashedFelt252Dict
https://github.com/lambdaclass/cairo_native/blob/ddfd28217c10f7202a03f10234f0a19113c46904/src/executor.rs#L783

We should be able to run the dict_with_struct.cairo, felt_dict_squash.cairo test
https://github.com/lambdaclass/cairo_native/blob/e89d38ad2f01bbd85c9f9de0b37841ac98661b50/tests/tests/cases.rs#L114
https://github.com/lambdaclass/cairo_native/blob/e89d38ad2f01bbd85c9f9de0b37841ac98661b50/tests/tests/cases.rs#L121

**Comment by tcoratger** [comment]
Can I take this one?
