### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo_native#632]
Improve the error handling in the repo
Right now we have just one general error type, This is OK, 
https://vscode.dev/github/lambdaclass/cairo_native/blob/main/src/error.rs#L12-L13

But the enum variants inside use mostly strings or aren't so descriptive. We should create a new module for those error variants and use enums instead of strings to describe the error.

check errors
```
Error(String),
ParseAttributeError,
```

**Comment by adrianvrj** [comment]
Hello, is this open for contribution?

I would like to work on this!

**Comment by adrianvrj** [comment]
Hey @pefontana I would love to work on this, could deliver it in 2-3 days!

**Comment by danielcdz** [comment]
Hey @pefontana I would like to help with this one, in the past I made contributions to Nethermind, this can take me about 1-2 days, as I already have some experience with Cairo

**Comment by Utilitycoder** [comment]
```rust
use std::{alloc::LayoutError, num::TryFromIntError};

#[derive(Error, Debug)]
pub enum Error {
    #[error(transparent)]
    LayoutError(#[from] crate::utils::LayoutError),

    #[error(transparent)]
    MlirError(#[from] melior::Error),

    #[error("missing parameter of type '{0}'")]
    MissingParameter(ParameterType),
}

pub enum ParameterType {
    TypeA,
    TypeB,
}
```

Is the above approach in line with the changes you have in mind for the error module? I agree that replacing string-based errors with structured and descriptive enum variants will enhance clarity.

**Comment by od-hunter** [comment]
Hi @pefontana ,Can I be assigned this issue? I’m ready to work.

**Comment by od-hunter** [comment]
Can i hop on this please?

**Comment by pefontana** [comment]
hi @od-hunter !
Yes sure!
i will assign it to you

**Comment by od-hunter** [comment]
@pefontana , Sorry I have been assigned other issues already and I’m working on them, in other not to disappoint you, kindly assign this to someone else, thank you 🙏🏾

**Comment by gadyrcdz** [comment]
Hi @pefontana, if this issue is still available I'd like to help!

**Comment by adrianvrj** [comment]
Hi, is this still open for contribution?
If so, can I hop on this?

**Comment by hart-venus** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/cairo-native).

### My background and how it can be leveraged
My background is in web development and low level systems, it can be leveraged to create effective and efficient error handling

### How I plan on tackling this issue
I would approach the problem by identifying error types, sorting those into an enum then  implementing them in rust, which would also need to be documented and written tests for.

**Comment by PriyankMkwna** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/cairo-native).

### My background and how it can be leveraged
I am a blockchain and DeFi developer . I am having experience of 8 months . I am currently working as a Blockchain Researcher and Developer. My Experience in programming language like Go , Rust , Java will help me to solve this issue.

**Comment by edg-l** [comment]
Closing as our error handling is already ok.
