### ISSUE TITLE
Fix nullable_box_vec.cairo error 

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo_native#633]
Fix the error when running the test 
https://github.com/lambdaclass/cairo_native/blob/89d44a113779307cc48b8577c5f40884995e0a05/tests/tests/cases.rs#L126

```
target/release/cairo-native-run --available-gas 9999999999 --single-file tests/cases/cairo_vm/nullable_box_vec.cairo
[1]    79047 segmentation fault  target/release/cairo-native-run --available-gas 9999999999 --single-fil
```

**Comment by adrianvrj** [comment]
Hi, can I work on this?

**Comment by EmmanuelAR** [comment]
Heyyy can i work in this? I can take less than 5 days

**Comment by Gerson2102** [comment]
Hey can i get this?

**Comment by igaray** [comment]
Hi @EmmanuelAR You are welcome to try but this one is likely to be very difficult. It will likely require: 
1. figuring out why it segfaults, by looking at the assembly
2. figuring out why the compiler generates the faulty assembly

**Comment by edg-l** [comment]
```
[runtime/src/lib.rs:240:5] "called dict gas refuned" = "called dict gas refuned"
[runtime/src/lib.rs:240:5] ptr = 0x0000000117fe5110
thread 'tests::cases::test_cases::_tests_cases_cairo_vm_nullable_box_vec_cairo_expects' panicked at src/values.rs:623:37:
misaligned pointer dereference: address must be a multiple of 0x8 but is 0x74
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The error is probably somewhere when parsing back the result, not within the execution
