### ISSUE TITLE
Cairo Native Stress Binary

### ISSUE THREAD

**Issue by JulianGCalderon** [lambdaclass/cairo_native#682]
related to #282 

Implement `cairo-native-stress` binary, which loops `n` times over the following sequence:
1. Generate an unique contract. Preferably in memory.
1. Test the contract with AOT, this implies:
    1. Compile it
    1. Cache it
    1. Run it
  
The output of this binary should answer the following questions:
- how many contracts until a segmentation fault?
- how much memory a cached program occupies?

Later on, we should test optimized versions of the cache, like:
- cache with eviction
- cache with write to disk

**Comment by zarah-s** [comment]
I'd love to have more details on this @JulianGCalderon

**Comment by JulianGCalderon** [comment]
Hi @zarah-s, i'm sorry. This issue had already been worked on by #683 and #686 , we forgot to close it when we merged those.
