### ISSUE TITLE
Segmentation fault in tx 0x74d05ea567909853f97889af773bf42f0655d5bccbd913c563e24638e829df8

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo_native#712]
To replicate it, run 
`cargo run tx 0x74d05ea567909853f97889af773bf42f0655d5bccbd913c563e24638e829df8 mainnet 648461` 
in the starknet replay crate in a computer with x86 architecture.  it should return Segmentation fault 

https://starkscan.co/tx/0x74d05ea567909853f97889af773bf42f0655d5bccbd913c563e24638e829df8

**Comment by edg-l** [comment]
i tried this locally and it didn't segfault with the jit executor, but it did with the aot executor
