### ISSUE TITLE
Add Workflow in CI to compare execution time in Native PR vs Main

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo_native#786]
Since we will focus on improving the performance of Cairo Native, we need to add a workflow in the CI that compares the execution time of the Native main branch vs. the PR. We have two similar workflows in the Cairo VM that can be used for inspiration.
https://github.com/lambdaclass/cairo-vm/actions/runs/10720771171/job/29727747406?pr=1830
<img width="1062" alt="image" src="https://github.com/user-attachments/assets/1b6b0f1a-284f-4f85-bf97-0401d28df3cf">

https://github.com/lambdaclass/cairo-vm/actions/runs/10720771156/job/29727939407?pr=1830

<img width="1023" alt="image" src="https://github.com/user-attachments/assets/faae2d5b-4574-4a9e-b38a-f4d0ecea4e4f">

Notes:
Ideally, we are interested in measuring the execution time, without taking the compilation part into account. But I'm not sure if that's possible with native. Maybe, the best approach is to have benchmarks in this repo that measure compilation time + execution time, and then create a script to measure the execution time in starknet replay.

**Comment by edg-l** [comment]
closing as completed
