### ISSUE TITLE
bug: malloc pointer being freed was not allocated

### ISSUE THREAD

**Issue by enitrat** [lambdaclass/cairo_native#801]
revision: 4355357697e9ab57ab88ae3a4282aac61455619e

I was trying to use cairo_native to run Kakarot's https://github.com/kkrt-labs/ef-tests test suite.
This test suite uses blockifier as a dependency to run transactions internally. We are using [Nethermind's fork of Blockifier](https://github.com/NethermindEth/sequencer) with Native integration to run these tests.

During the execution of one of our tests, the program crashed with:

```
VMTests-180788a4976cce5c(34821,0x16bd3b000) malloc: *** error for object 0x600015eb19a0: pointer being freed was not allocated
VMTests-180788a4976cce5c(34821,0x16bd3b000) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by edg-l** [comment]
Can you try with a newer commit? There have been some fixes over time since that one.

**Comment by enitrat** [comment]
hm, wasn't able to reproduce this specific error after updating, now I'm getting an error saying that 

```
Native execution error: Entrypoint selector 223977839602597075282304712325742725558906266213235334744709008060623732285 not found
```

so it's probably more an error from the blockifier side? But perhaps the native compilation went wrong?

**Comment by enitrat** [comment]
We can close this one and I can open another one for the problem above. I'm wondering if it's due to the new `ignore_debug_names` flag?

**Comment by edg-l** [comment]
> We can close this one and I can open another one for the problem above. I'm wondering if it's due to the new `ignore_debug_names` flag?

Did you update blockifier to use the ContractExecutor? 
I dont recall this error from cairo-native side, native doesn't really have any notion about selectors, i would say its probably coming from blockifier, maybe the syscall handler (library_call or contract call?)

**Comment by enitrat** [comment]
I'm waiting for NM to update blockifier - will update next week.

**Comment by enitrat** [comment]
Hey, I updated to use the ContractExecutor - still getting the same issue.
