### ISSUE TITLE
bug: inconsistent dict values in Native execution?

### ISSUE THREAD

**Issue by enitrat** [lambdaclass/cairo_native#808]
CASM execution:
```
stack_push top 0
stack_push top 0
stack_push top 0
stack_push top 0
stack_push top 0
stack_push top 4
stack_pop top 4
```

Native execution:
```
stack_push top 0
stack_push top 0
stack_push top 0
stack_push top 0
stack_push top 0
stack_push top 4
stack_pop top 0
```

Trying to debug why native would fail our EF-Tests.

Repro:
scarb 2.8.2
clone https://github.com/kkrt-labs/kakarot-ssj
`git checkout temp/debug native`
`scarb build -p contracts` - builds the required contract with some debug print logs
diff with main is only prints: https://github.com/kkrt-labs/kakarot-ssj/pull/973

clone https://github.com/kkrt-labs/ef-tests
ensure correct branch `git checkout feat/cairo-native`
`make`
`make setup-kakarot`
copy the contracts built previously:`cp ../kakarot-ssj/target/dev/contracts_* build/v1`
`cargo test mulmod_d0g0v0_Cancun --features v1,native -- --nocapture` (with LLVM19)

Relevant Cairo code
https://github.com/kkrt-labs/kakarot-ssj/blob/29ace538518990a108ba30b3d0a690b2c8ca0724/crates/evm/src/stack.cairo

**Comment by edg-l** [comment]
closing as fixed
