### ISSUE TITLE
State Diff: Truncated Storage Value: 0x1ce1460cf29b2439b458263b121c7a82651b77dab69f861a9850eb2145eb3ab

### ISSUE THREAD

**Issue by JulianGCalderon** [lambdaclass/cairo_native#820]
Tx 0x1ce1460cf29b2439b458263b121c7a82651b77dab69f861a9850eb2145eb3ab differs when comparing with Cairo VM.

Traces:
- [Native](https://github.com/user-attachments/files/17168358/0x1ce1460cf29b2439b458263b121c7a82651b77dab69f861a9850eb2145eb3ab.json)
- [VM](https://github.com/user-attachments/files/17168347/0x1ce1460cf29b2439b458263b121c7a82651b77dab69f861a9850eb2145eb3ab.json)

This was recorded with trace dump feature in starknet-replay: https://github.com/lambdaclass/starknet-replay/pull/58

Other transactions with similar bug:
- 0x7192cb38bf8414ce0a88fe678a156e742b99371e38174d947d9fedf4f98ff3
- 0x759fd709b0986e42f91319b143a8b3e7ffc695c828eae2eed4b24dfb9a7de63
- 0x1eb296226969571bc17d335f9db894bd817edd12064d2e1c86d5f5d414bf6b6
- 0x4d492ccfb9b924b79289046f7607ce0c949497c5f431af48e81b8705f53e6af
- 0x2b043bb30da7b8d4ac83ec31f48fb17ff14d8c51584ba91031ba0afede55597
- 0x3bcf976c04d9d147537138891b59c12a43c257487343f6106609437e81257e0

**Comment by JulianGCalderon** [comment]
Transaction 0x7192cb38bf8414ce0a88fe678a156e742b99371e38174d947d9fedf4f98ff3 appears to have a similar bug

**Comment by JulianGCalderon** [comment]
All transaction diffs look like this: different numbers, same pattern.

<img width="1277" alt="image" src="https://github.com/user-attachments/assets/6d1aac04-a042-41a5-8d3f-43e2a6288220">

**Comment by pefontana** [comment]
Just to add info here. This states dumpls where generated running the block range 742000 to 742644
```
cargo run --release --features state_dump block-range 742000 742644 mainnet
cargo run --release --features state_dump,onlt_cairo_vm block-range 742000 742644 mainnet
```
