### ISSUE TITLE
StateDiff mismatch in Storage

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo_native#846]
Running Starknet Replay with state_dump, native vs VM, there is a mismatch in State's storage 
Txs:
* block747113/0x6310e7dc70754b898689fd45a5242c8a6a97875c3634cae4d0bd27befe43194
* block747114/0x6d431daaaad5abc84d903769da37b4982e913e1333a8022b847d8ad72afb739

### commits
Cairo Native: 82c25b377f50904e1253b614c8719388277530e6
Starknet replay: e125989afa77022995b3989c1d64292755312a87
blockifier = { git = "https://github.com/lambdaclass/sequencer", branch = "native2.8.x"},  1eaaa4b9902cd9f4a867b111ca87c3a3bfce5d29

**Comment by FrancoGiachetta** [comment]
In order to reproduce this diffs it's necessary to run the whole block

**Comment by pefontana** [comment]
Fixed
https://github.com/lambdaclass/starknet-replay/pull/75
https://github.com/lambdaclass/cairo_native/pull/874
