### ISSUE TITLE
StateDiff mismatch in Nonce

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo_native#847]
Running Starknet Replay with state_dump, native vs VM, there is a mismatch in State's nonce track
Txs:
* block747115/0x281d91c5ee939b6548e1e039b381b3f6e5c200f5808b3ef389bbbd6fdb0c6ec
* block747122/0x469cd089b00448e2816aa799299bafc50d160850fd25f1d34c1926929833b05
* block747113/0x6310e7dc70754b898689fd45a5242c8a6a97875c3634cae4d0bd27befe43194
* block749209/0x770f05cb6d47bd3ce54422d06742b45da92d21f23f4f33b4cd4d00d501000b3

### commits
Cairo Native: 82c25b377f50904e1253b614c8719388277530e6
Starknet replay: e125989afa77022995b3989c1d64292755312a87
blockifier = { git = "https://github.com/lambdaclass/sequencer", branch = "native2.8.x"},  1eaaa4b9902cd9f4a867b111ca87c3a3bfce5d29

**Comment by JulianGCalderon** [comment]
I think `0x469cd089b00448e2816aa799299bafc50d160850fd25f1d34c1926929833b05` diff is caused by the previous tx (`0x1575f53142109a24350541cf9a6019390f298478b0b2757157c818a3b74cf51`). The previous tx reverts in Native, but not in CairoVM. 

This is missed by the state dump feature as the unexpected error causes the state dump of `0x1575f53142109a24350541cf9a6019390f298478b0b2757157c818a3b74cf51` to not even be generated.

- Cairo Native:
   ```
  2024-10-14T22:18:16.278546Z ERROR replay: execution failed unexpectedly: Transaction validation has failed:
  0: Error in the called contract (
    contract address: 0x010b685e795f70a7fb32d473878154e38a2668372dfe5d01d6cbdd9309d1be7f,
    class hash: 0x032e17891b6cc89e0c3595a3df7cee760b5993744dc8dfef2bd4d443e65c0f40,
    selector: 0x0162da33a4585851fe8d3af3c2a9c60b557814e221e0d4f30ff0b2189d9c7775):
  Native execution error: invalid-owner-sig
   ```
- Cairo VM:
   ```
   2024-10-14T22:16:06.878264Z  INFO replay: execution finished successfully, 
     transaction_hash: "0x1575f53142109a24350541cf9a6019390f298478b0b2757157c818a3b74cf51",
     chain: "mainnet",
     execution_status: "SUCCEEDED", rpc_execution_status: "SUCCEEDED",
     n_events_and_messages: "{ events_number: 4, l2_to_l1_messages_number: 0 }",
     rpc_n_events_and_msgs: "{ events_number: 4, l2_to_l1_messages_number: 0 }",
     da_gas: "{ l1_da_gas: 448, l1_gas: 0 }",
     state_changes_for_fee_str: "{ n_class_hash_updates: 0, n_compiled_class_hash_updates: 0, n_modified_contracts: 2, n_storage_updates: 5 }"
   ```

**Comment by pefontana** [comment]
Fixed here
https://github.com/lambdaclass/starknet-replay/pull/75
https://github.com/lambdaclass/cairo_native/pull/874
