### ISSUE TITLE
[BUG] Storage Diffs

### ISSUE THREAD

**Issue by FrancoGiachetta** [lambdaclass/cairo_native#887]
Running these blocks in linux `803072`, `805651` generates diffs in the state_dump, particularly related to storage writes. 

In mac only happens with block `803072`.

<img width="1199" alt="Screenshot 2024-10-25 at 5 24 59 PM" src="https://github.com/user-attachments/assets/9a9d01f6-1ebd-407f-9dd6-8e6e423a7934">

**Comment by FrancoGiachetta** [comment]
Couldn't find the tx which produces the diff. I think is the one shown in the picture. [link](https://starkscan.co/tx/0x031eebe3d49e38f44c63490f134e35acb4754f68bf0cb7250bc70124ff2b9599)

Running this tx results in seg fault, which why I cannot be sure yet if this is the target tx

**Comment by edg-l** [comment]
The linked tx runs without a segfault on native (without trace dump feature)

```
  2024-10-28T08:43:22.267361Z ERROR replay: rpc and execution status diverged, transaction_hash: "0x031eebe3d49e38f44c63490f134e35acb4754f68bf0cb7250bc70124ff2b9599", chain: "mainnet", reverted: true, rpc_reverted: false, root_of_error: "EXECUTION STATUS DIVERGED", execution_error_message: "Transaction execution has failed:\n0: Error in the called contract (contract address: 0x055e557a4c975059522a1321d7a7bd215287450907419e5f8aa98145c7699a2c, class hash: 0x01a736d6ed154502257f02b1ccdf4d9d1089f80811cd6acad48e6b6a9d1f2003, selector: 0x015d40a3d6ca2ac30f4031e42be28da9b056fef9bb7357ac5e85627ee876e5ad):\nNative execution error: argent/multicall-failed\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0Native execution error: Native execution error: INVALID_SIG\n", n_events_and_messages: "{ events_number: 1, l2_to_l1_messages_number: 0 }", rpc_n_events_and_msgs: "{ events_number: 11, l2_to_l1_messages_number: 0 }", da_gas: "{ l1_da_gas: 128, l1_gas: 0 }", state_changes_for_fee_str: "{ n_class_hash_updates: 0, n_compiled_class_hash_updates: 0, n_modified_contracts: 1, n_storage_updates: 1 }"
    at replay/src/main.rs:350
    in replay::transaction with hash: "0x031eebe3d49e38f44c63490f134e35acb4754f68bf0cb7250bc70124ff2b9599", chain: "mainnet"
```

**Comment by FrancoGiachetta** [comment]
Yes, sorry, forgot to mention the seg fault happens with the trace-dump feature activated.

**Comment by FrancoGiachetta** [comment]
Update

I've noticed that the value `0xc8e72e` (the one which differs from vm) is already in the storage when the block is executed. Which could mean that perhaps there's no issue with native. In fact, this happens  both in sierra-emu and native. Due to this,  I can't really say where the issue is, and why does the vm have a different value compared to native.

**Comment by FrancoGiachetta** [comment]
Update

Changed to block `805651`. The first tx which produces the error is [this](https://starkscan.co/tx/0x0253dab7e810df7b42ce2c5800ee4b3f2e505fd9d98700e65079c7cd29953580) one. So probably, if there's any error with native, it trace should give us some information. Running it the trace-dump also produces an error. This seg fault it related to issue #840, seems like theres something wrong related to `FeltDict` whenever the `with-trace-dump` feature is activated. 

However, this issue seems quite rare. I've run many transactions in hope of finding any libfunc which could be generated wrong values, but without success. Thus, I cannot tell if this is a native's error of something else. Running it on mac produces the some error. Nevertheless, the state-dump of some of the transactions differs from the one on linux.

**Comment by JulianGCalderon** [comment]
Found another transaction that seems to differ for the same reasons:
- Block: 802989
- Tx: 0x210ce63684fbd1f69d1a444316abad7b3b06e62152c97af9cb4e5d0d53d1bc8

```
*** NATIVE
--- VM
***************
*** 3540,3546 ****
            "0x2bd1cdd5f7f17726ae221845afd9580278eebc732bc136fe59d5d94365effd5",
            "0x7826c37287c9fff392d1338f7e594122bf4390397007b8a707bb799aea6cdd6"
          ],
!         "0x549bec2"
        ],
        [
          [
--- 3540,3546 ----
            "0x2bd1cdd5f7f17726ae221845afd9580278eebc732bc136fe59d5d94365effd5",
            "0x7826c37287c9fff392d1338f7e594122bf4390397007b8a707bb799aea6cdd6"
          ],
!         "0x800000000000010fffffffffffffffffffffffffffffffffffffffffab6413f"
        ],
        [
          [
***************
*** 3589,3595 ****
            "0x69823f8677ebcc3cc4eb14ff93ccadc4873ec83fbf6afa643ee813f929638bc",
            "0x14b3c33c6ffdbf8a251b4dab288ba592ee7ecd4a41d941b0bd7bcf63dfa7b2"
          ],
!         "0xd0d820"
        ],
        [
          [
--- 3589,3595 ----
            "0x69823f8677ebcc3cc4eb14ff93ccadc4873ec83fbf6afa643ee813f929638bc",
            "0x14b3c33c6ffdbf8a251b4dab288ba592ee7ecd4a41d941b0bd7bcf63dfa7b2"
          ],
!         "0x800000000000010ffffffffffffffffffffffffffffffffffffffffff2f27e1"
        ],
        [
          [
```

**Comment by JulianGCalderon** [comment]
Found another transaction that seems to differ for the same reasons:

- Block: 802989
- Tx: 0x629b7b1a726e883da45ab9e71e1f3f0e91bd2df00ffd8417a7c2c77e2f56d32


```
*** Native
--- VM
***************
*** 3532,3538 ****
            "0x12442a0c5b35b8f3d72385c8dbfe832701cd2db7bc547a5429d1c03b5530774",
            "0x14b3c33c6ffdbf8a251b4dab288ba592ee7ecd4a41d941b0bd7bcf63dfa7b2"
          ],
!         "0x3923dc"
        ],
        [
          [
--- 3532,3538 ----
            "0x12442a0c5b35b8f3d72385c8dbfe832701cd2db7bc547a5429d1c03b5530774",
            "0x14b3c33c6ffdbf8a251b4dab288ba592ee7ecd4a41d941b0bd7bcf63dfa7b2"
          ],
!         "0x800000000000010ffffffffffffffffffffffffffffffffffffffffffc6dc25"
        ],
        [
          [
***************
*** 3665,3671 ****
            "0x2bd1cdd5f7f17726ae221845afd9580278eebc732bc136fe59d5d94365effd5",
            "0x417a48900e62ab593d3b27e6523b285f673a54e7f5956feae5fc4aba8061ed"
          ],
!         "0x3923dc"
        ],
        [
          [
--- 3665,3671 ----
            "0x2bd1cdd5f7f17726ae221845afd9580278eebc732bc136fe59d5d94365effd5",
            "0x417a48900e62ab593d3b27e6523b285f673a54e7f5956feae5fc4aba8061ed"
          ],
!         "0x800000000000010ffffffffffffffffffffffffffffffffffffffffffc6dc25"
        ],
        [
          [
```
