### ISSUE TITLE
Build fails when disabling default features

### ISSUE THREAD

**Issue by kkovaacs** [lambdaclass/cairo_native#983]
I'm testing with Cairo Native commit `f53c9479d69c7dbd6dd568d9a06160c4f2e784dc`.

Cairo Native cannot be built when disabling the default features. I was primarily looking into disabling the `build-cli` because in our project ([Pathfinder](https://github.com/eqlabs/pathfinder)) we don't need the CLI tools. Turns out there are some dependencies that were meant to be used only in the CLI parts but have crept into non-CLI "core" code, for example:

```
% cargo check --all-targets --no-default-features
    Checking cairo-native v0.2.5 (/home/hidden/Source/github.com/starkware-libs/sequencer/crates/blockifier/cairo_native)
error[E0432]: unresolved import `cairo_lang_runner`
 --> src/metadata/gas.rs:1:5
  |
1 | use cairo_lang_runner::token_gas_cost;
  |     ^^^^^^^^^^^^^^^^^ use of undeclared crate or module `cairo_lang_runner`
  |
help: there is a crate or module with a similar name
  |
1 | use cairo_lang_utils::token_gas_cost;
  |     ~~~~~~~~~~~~~~~~
```

This is unfortunate, as this means that I cannot add cairo_native as a _library_ into our project without building the unnecessary runtime / CLI parts.

**Comment by azteca1998** [comment]
It seems that a few bin-only dependencies have been filtered into the library. I'll let you know once it's fixed. It shouldn't take long.

**Comment by azteca1998** [comment]
The issue seems to have been fixed. You can now build the stripped version of the library. Keep in mind that to support some functionality of the compiler, such as (but not limited to):
  - Elliptic curves
  - Pedersen and poseidon hashing
  - The print libfunc
  - The AOT executor

you'll need to enable the runtime.

The command you used in the issue has the `--all-targets` flag and doesn't specify that it should only check the library, that's why it'll crash anyways after the fix. The correct command would be:
```sh
cargo check \
    --no-default-features \  # Disable default features.
    --lib                 \  # Only check the library (not the binaries).

# To run `cargo check` with the runtime enabled:
cargo check \
    --no-default-features.  \  # Disable default features.
    --lib                   \  # Only check the library (not the binaries).
    --features=with-runtime    # Enable the runtime
```

**Comment by kkovaacs** [comment]
Thanks for the fix. Indeed, it builds fine with these changes. I was mostly interested in disabling the CLI bits to avoid pulling in the additional dependencies for parts we don't even need.
